### PR TITLE
Editing Report

### PR DESCRIPTION
**Pull request by thomasrussellmurphy**
This was necessary before submission, but I'd like to do this now to have a presentable report to post elsewhere.
Things to get done in the revisions:
  - [x] Fixing small (some severe) typos
  - [x] Removing piles of leftover template material
  - [ ] Uniform tense as appropriate
  - [ ] Check clarity throughout document

### CODE REVIEW

**Comment by thomasrussellmurphy** [comment]
(Lolfinals, this will happen eventually)

**Comment by thomasrussellmurphy** [comment]
Any comments prior to merge?

**Comment by brenns10** [comment]
I'm gonna go out on a limb and say that, since class is done, none of us care that much. So that's a +1 from me.

:shipit:

**Comment by ajm188** [comment]
Seconded

**Comment by thomasrussellmurphy** [comment]
Shipping.

**Pull request merged**
